#!/usr/bin/env sh
function help()
{
    echo "Usage: icfs_create_disk_pool -m <codenumber> -s <hostname> [<hostname>...]"
    echo "Help options:"
    echo "  -m <codenumber>              number of coding chunks"
    echo "                               is integer and between 2 and 4, default 2 "
    echo "  -s                           enable split ssd sata"                                                                                                                 
    echo "  <hostname>                   [<hostname>...] the hostname of server node"
    echo "  -h|? :Show this help message"
}

if [ $# -lt 1 ] ; then
	help
	exit 2
fi

m_value=2
sdsa_enable=0
hargs_index=1
server_array=()
args_array=("$@")

if [ "$1" == "-h" ] || [ "$1" == "?" ] || [ "$1" == "-?" ] ; then
	help
	exit 1
fi

if [ "$1" == "-m" ] || [ "$1" == "-s" ] ; then
	if [ "$1" == "-m" ] && [ $# -ge 3 ] ; then
		if [ $2 -le 4 ] && [ $2 -ge 2 ] ; then
			m_value=$2
			if [ "$3" == "-s" ] && [ $# -ge 4 ] ; then 
				hargs_index=4
				sdsa_enable=1
			else if [ "$3" != "-s" ] ; then
				hargs_index=3
			else
				printf "[Error] Parameters is Illegal, Please check Parameters and try again !\n\n"
				help
				exit 3
			fi
			fi
		else
			printf "[Error] Parameters is Illegal, Please check Parameters and try again !\n\n"
			help
			exit 3
		fi
	else
	    if [ "$1" == "-s" ] && [ $# -ge 2 ] ; then
    	    if [ "$2" == "-m" ] && [ $# -ge 4 ] ; then
        	    if [ $3 -le 4 ] && [ $3 -ge 2 ] ; then
            	    sdsa_enable=1
                	m_value=$3
                	hargs_index=4
            	else
					printf "[Error] Parameters is Illegal, Please check Parameters and try again !\n\n"
                	help
                	exit
            	fi
        	else
				if [ "$2" != "-m" ] ; then
					sdsa_enable=1
					hargs_index=2
				else
					if [ $# -le 3 ] ; then
						printf "[Error] Parameters is Illegal, Please check Parameters and try again !\n\n"
						help
						exit
					fi
				fi
        	fi
    	else
			printf "[Error] Parameters is Illegal, Please check Parameters and try again !\n\n"
        	help
        	exit 3
    	fi
	fi
else
	hargs_index=1	
fi

i=$hargs_index
array_size=1
while [ $i -le $# ]
do
	server_array[$array_size]=${args_array[$i-1]}

    exist=`cat /etc/hosts | grep -w "${server_array[$array_size]}" | awk '{print$2}'`
    if [ -z $exist ] ; then
        printf "[Error] hostname: ${server_array[$array_size]} is not resolvable !\n\n"
        exit 1
    #else
        #ssh -t ${server_array[$array_size]} create_disk_pool >/dev/null 2>&1
        #osd_num=$?
        #remainder=`echo "$osd_num"%"$m_value" | bc`
        #if [ 0 -ne $remainder ] ; then
        #    echo "[Warning] The osdnum of ${server_array[$array_size]} must be balanced !"
        #    exit 1
        #fi
    fi

	let i+=1
	let array_size+=1
done
let array_size-=1

mpool_osd_coll=`cat /tmp/mpool_osd`
for arg in ${server_array[@]}
do
	ssh -t $arg "create_disk_pool $m_value $sdsa_enable $mpool_osd_coll"
done

