#!/bin/sh

usage()
{
  echo "Usage: ceph-dir-export <the path to be assigned> <src mds> <destination mds>"
  echo ""
  echo "       --<the path to be assigned>      already exist. the path began to write from the mounted file system root"
  echo "       --<src mds>                      active MDS, the path originally belonged "
  echo "       --<destination mds>              active MDS, the path is about to belong. cannot be the same with <src mds>."
  echo ""
  echo "For example:"
  echo "              ceph-dir-export a 0 1"
#  echo "              ceph-dir-export a/b/c 1 2"
}
echo  "Program preparation ..."
if [ $# -ne 3 ]; then
  usage
  exit 0
fi
(( $2 )) 2>/dev/null
if [[ $? -ne 0 ]]; then
  if [ $2 -eq 0 ] 2>/dev/null; then
    break
  else
    echo "ERROR: the second parameter is not an integer"
    exit 0
  fi
fi
(( $3 )) 2>/dev/null
if [[ $? -ne 0 ]]; then
  if [ $3 -eq 0 ] 2>/dev/null; then
    break
  else
    echo "ERROR: the third parameter is not an integer"
    exit 0
  fi
fi


echo `ceph -s | grep mdsmap | grep -o '\{.*\}' | cut -d '{' -f 2 | cut -d '}' -f 1 | cut -d ',' -f 1` > inspur_tmpfile1
echo `ceph -s | grep mdsmap | grep -o '\{.*\}' | cut -d '{' -f 2 | cut -d '}' -f 1 | cut -d ',' -f 2` >> inspur_tmpfile1
echo `ceph -s | grep mdsmap | grep -o '\{.*\}' | cut -d '{' -f 2 | cut -d '}' -f 1 | cut -d ',' -f 3` >> inspur_tmpfile1
cat inspur_tmpfile1 | grep active | awk -F"=" '{print $1}' > inspur_tmpfile2
ARRAY=(`awk '{print $1}' inspur_tmpfile2`)
bool1=false
bool2=false
if [ $2 -eq $3 ]; then
  echo "ERROR: The second parameter can not equal to the third parameter."
  exit 0
fi
for((i=0;i<${#ARRAY[*]};i++))
do
  if [ $2 -eq "${ARRAY[i]}" ]; then
  {
    bool1=true
    break
  }
  fi
done
if [ "$bool1" == "false" ]; then
  echo "ERROR: The second parameter should be active mds number. "
  exit 0
fi
for((i=0;i<${#ARRAY[*]};i++))
do
  if [ $3 -eq "${ARRAY[i]}" ]; then
  {
    bool2=true
    break
  }
  fi
done
if [ "$bool2" == "false" ]; then
  echo "ERROR: The third parameter should be active mds number. "
  exit 0
fi
rm -rf inspur_tmpfile1
rm -rf inspur_tmpfile2
mkdir /mnt/inspur01233210 >/dev/null 2>&1
ceph-fuse -c /etc/ceph/ceph.conf /mnt/inspur01233210 >/dev/null 2>&1
sleep 3
cd /mnt/inspur01233210
if [ ! -d $1 ]; then
  echo "ERROR: The first parameter is not a path."
  exit 0
fi
echo -n "The program is running ..."
cd /mnt/inspur01233210/$1
touch .inspur
cd /root
ceph mds tell $2 export_dir $1 $3 >/dev/null 2>&1
echo " ..."
rm -rf /mnt/inspur01233210/$1/.inspur
umount /mnt/inspur01233210
rm -rf /mnt/inspur01233210

