#!/bin/sh

usage()
{
  echo "Usage: ceph-set-max-mds <int[1-3]>"
  echo "       --<int[1-3]>        The number of cluster active MDS"
}
if [ $# -ne 1 ]; then
  usage
  exit 0
fi
(( $1 )) 2>/dev/null
if [[ $? = 0 ]]; then
  if [[ $1 -gt 3 ]] || [[ $1 -lt 1 ]] || [[ $1 -eq 0 ]]; then
    echo "the parmeter is invalid. Forced to use the default value 3"
    ceph mds set_max_mds 3
  else
    ceph mds set_max_mds $1
  fi
elif [ $1 -eq 0 ] 2>/dev/null; then
  echo "the parmeter is invalid. Forced to use the default value 3"
  ceph mds set_max_mds 3
else  
  echo "ERROR: the parameter is not an integer"
  exit 0
fi
